export const navConfig = {
  pages: [
    {
      title: "Intro",
      link: "/intro",
      subnav: [],
    },
    {
      title: "So, what's an SVG?",
      link: "/whatis",
      subnav: [],
    },
    {
      title: "SVG Syntax",
      link: "/syntax",
      subnav: [],
    },
    {
      title: "Basic Shape Elements",
      link: "/shapes",
      subnav: [],
    },
    {
      title: "Paths",
      link: "/paths",
      subnav: [],
    },
    {
      title: "Text",
      link: "/text",
      subnav: [],
    },
    {
      title: "Presentation Attributes",
      link: "/presentation-attributes",
      subnav: [],
    },
    {
      title: "Styles",
      link: "/styles",
      subnav: [],
    },
    {
      title: "Colors",
      link: "/colors",
      subnav: [],
    },
    {
      title: "Groups",
      link: "/groups",
      subnav: [],
    },
    {
      title: "Transforms",
      link: "/transforms",
      subnav: [],
    },
    {
      title: "Reusable Objects",
      link: "",
      subnav: [
        { title: "use", link: "/reusable-use" },
        { title: "defs", link: "/reusable-defs" },
        { title: "markers", link: "/reusable-markers" },
        { title: "gradients", link: "/reusable-gradients" },
        { title: "patterns", link: "/reusable-patterns" },
        { title: "clip-paths", link: "/reusable-clippath" },
        { title: "masks", link: "/reusable-mask" },
        { title: "filters", link: "/reusable-filter" },
      ],
    },
    {
      title: "Dynamic Changes",
      link: "",
      subnav: [
        { title: "changing attributes", link: "/dynamic-changing" },
        { title: "generating elements", link: "/dynamic-generating" },
        { title: "dragging elements", link: "/dynamic-dragging" },
      ],
    },
    {
      title: "Animation",
      link: "",
      subnav: [
        { title: "intro", link: "/animation-intro" },
        { title: "css", link: "/animation-css" },
        { title: "more css", link: "/animation-css-II" },
        { title: "javascript", link: "/animation-javascript" },
        { title: "more javascript", link: "/animation-javascript-II" },
        { title: "SMIL", link: "/smil-animation" },
        { title: "more SMIL", link: "/smil-animation-II" },
        { title: "Sprites", link: "/sprites" },
      ],
    },
    {
      title: "Physics with Matter.js",
      link: "",
      subnav: [
        { title: "matter.js intro", link: "/matterjs-intro" },
        { title: "creating a particle", link: "/matterjs-particles" },
        { title: "multiple particles", link: "/matterjs-particles-multiple" },
        { title: "square particles", link: "/matterjs-particles-squares" },
        { title: "polygon particles", link: "/matterjs-particles-polygons" },
        { title: "svg path particles", link: "/matterjs-particles-svgbodies" },
        { title: "applying forces", link: "/matterjs-particles-forces" },
      ],
    },
    {
      title: "GreenSock Animation",
      link: "",
      subnav: [
        { title: "GSAP intro", link: "/greensock-intro" },
        { title: "tweening methods", link: "/greensock-methods" },
        { title: "timelines", link: "/greensock-timelines" },
        { title: "playback controls", link: "/greensock-playback-controls" },
      ],
    },
    {
      title: "Aspect Ratio",
      link: "/aspect-ratio",
      subnav: [],
    },
  ],
  links: [
    { title: "Intro", link: "/intro" },
    { title: "So, what's an SVG?", link: "/whatis" },
    { title: "SVG Syntax", link: "/syntax" },
    { title: "Basic Shape Elements", link: "/shapes" },
    { title: "Paths", link: "/paths" },
    { title: "Text", link: "/text" },
    { title: "Presentation Attributes", link: "/presentation-attributes" },
    { title: "Styles", link: "/styles" },
    { title: "Colors", link: "/colors" },
    { title: "Groups", link: "/groups" },
    { title: "Transforms", link: "/transforms" },
    { title: "use", link: "/reusable-use" },
    { title: "defs", link: "/reusable-defs" },
    { title: "markers", link: "/reusable-markers" },
    { title: "gradients", link: "/reusable-gradients" },
    { title: "patterns", link: "/reusable-patterns" },
    { title: "clip-paths", link: "/reusable-clippath" },
    { title: "masks", link: "/reusable-mask" },
    { title: "filters", link: "/reusable-filter" },
    { title: "changing attributes", link: "/dynamic-changing" },
    { title: "generating elements", link: "/dynamic-generating" },
    { title: "dragging elements", link: "/dynamic-dragging" },
    { title: "intro", link: "/animation-intro" },
    { title: "css", link: "/animation-css" },
    { title: "more css", link: "/animation-css-II" },
    { title: "javascript", link: "/animation-javascript" },
    { title: "more javascript", link: "/animation-javascript-II" },
    { title: "SMIL animation", link: "/smil-animation" },
    { title: "more SMIL", link: "/smil-animation-II" },
    { title: "Sprites", link: "/sprites" },
    { title: "matter.js intro", link: "/matterjs-intro" },
    { title: "particles", link: "/matterjs-particles" },
    { title: "multiple particles", link: "/matterjs-particles-multiple" },
    { title: "square particles", link: "/matterjs-particles-squares" },
    { title: "polygon particles", link: "/matterjs-particles-polygons" },
    { title: "svg path particles", link: "/matterjs-particles-svgbodies" },
    { title: "applying forces", link: "/matterjs-particles-forces" },
    { title: "GSAP intro", link: "/greensock-intro" },
    { title: "tweening methods", link: "/greensock-methods" },
    { title: "timelines", link: "/greensock-timelines" },
    { title: "playback controls", link: "/greensock-playback-controls" },
    { title: "Aspect Ratio", link: "/aspect-ratio" },
  ],
};
